### ISSUE TITLE
Alipay and WeChat Payment Types

### ISSUE THREAD

**Issue by WeAreELIC** [joshnuss/svelte-stripe-js#11]
I would love to see Alipay and WeChat payment types supported so our China customers can easily pay. Thanks!

**Comment by joshnuss** [comment]
Hi @WeAreELIC,

I'm not too familiar with WeChat and AliPay, but I believe a custom Svelte component isn't needed for these because the payment is completed with a redirect, so any button will do.

From reading the docs, the flow works like this:

1. Add a button "Pay with WeChat" or "Pay with AliPay"
2. When the button is clicked, `POST` to server to create the `PaymentIntent` (using `payment_method_types: ["alipay"]` or `payment_method_types: ["wechat_pay"]` and then return the `PaymentIntent`'s `client_secret`
3. Using that `client_secret`, call `stripe.confirmWechatPayPayment(client_secret)` or `stripe.confirmAlipayPayment(client_secret)`. That will redirect the user to their wallet.

Stripe's docs:
- AliPay https://stripe.com/docs/payments/alipay/accept-a-payment
- WeChat https://stripe.com/docs/payments/wechat-pay/accept-a-payment

Let me know if you have questions
