### ISSUE TITLE
Your example for credit card "cardElement" is not declared

### ISSUE THREAD

**Issue by mylastore** [joshnuss/svelte-stripe-js#23]
How to declare cardElement?

**Comment by joshnuss** [comment]
Hi @mylastore!

You can find an example of declaring a `cardElement` here:
https://github.com/joshnuss/svelte-stripe-js/blob/dfe3338fa32d5530f8a274e21d5dc73c4eca3823/src/routes/examples/credit-card/index.svelte#L26

Closing this issue, since I think it answers the question. Feel free to re-open if you have further questions about this
